### ISSUE TITLE
Suggestion for 2019

### ISSUE THREAD

**Issue by ppKrauss** [amer-ali/jsontron#1]
Hi,  good initiative!  It is the first one that I see as real "Schematron for JSON".

... Thinking in some suggestions to gain some more "attractiveness" inthe rule syntax:

1. JSON-path syntax: use of [JSON Pointer](https://tools.ietf.org/html/rfc6901#section-5), or alternativally a set of path-operators like [the pg-json operators](https://www.postgresql.org/docs/current/functions-json.html).
  
2. Look for some compatibility with [json-schema-core](http://json-schema.org/latest/json-schema-core.html)... As in the XML's Schematron-Schema relation, is good because is a complement.

3. Try to use the syntax of modern Javascript [destructuring-assignments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). 

And...  Add some explicit invitation in the README. Invite new members to your project, any good "standard proposal" need a big communuty to get a chance to be a *standard* or reference-implamentation in  the future...  Any [*de facto* standard](https://en.wikipedia.org/wiki/De_facto_standard)  grows from collective relations.

**Comment by amer-ali** [comment]
Thanks @ppKrauss for your valuable suggestions. Would love to add experts like you to the project.

**Comment by amer-ali** [comment]
Thanks @ppKrauss
